# Generated by Django 5.0.7 on 2024-08-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_id_facility_event_facility_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='id_sport',
            new_name='sport',
        ),
    ]
