# Generated by Django 5.0.7 on 2024-08-07 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='datetime',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date(2024, 8, 7)),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default='20:00'),
        ),
    ]
